name: Code Climate Test Reporter
description: Send test coverage results to code climate
author: aktions
branding:
  icon: code
  color: green
inputs:
  codeclimate-test-reporter-id:
    description: The test reporter ID. This is a write-only ID that can only post test reports
    required: true
  codeclimate-test-reporter-version:
    description: The test reporter version. By default "latest" is used
    default: latest
  codeclimate-test-reporter-url:
    description: The test reporter download URL. If supplied, it will override the version, os and architecture input
  command:
    description: The command to execute using the codeclimate test reporter
    default: after-build
runs:
  using: node12
  main: dist/index.js

